# Generated by Django 5.0.3 on 2024-08-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyFatPercentageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyFatPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyFatPercentageHistory', to='user_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleMassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleMass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscleMassHistory', to='user_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightHistory', to='user_profile.profile')),
            ],
        ),
    ]
